create table movies (
	id INT,
	movie_title VARCHAR(150),
	movie_genre VARCHAR(150),
	movie_rating DECIMAL(2,1)
);
insert into movies (id, movie_title, movie_genre, movie_rating) values (1, 'Who the F**K Is Arthur Fogel', 'Documentary', 9.1);
insert into movies (id, movie_title, movie_genre, movie_rating) values (2, 'Cousin cousine', 'Comedy|Romance', 9.2);
insert into movies (id, movie_title, movie_genre, movie_rating) values (3, 'Dungeons & Dragons', 'Adventure|Fantasy', 3.6);
insert into movies (id, movie_title, movie_genre, movie_rating) values (4, 'Doll''s House, A', 'Drama', 6.1);
insert into movies (id, movie_title, movie_genre, movie_rating) values (5, 'Kino-Eye (Kinoglaz)', 'Documentary', 8.8);
insert into movies (id, movie_title, movie_genre, movie_rating) values (6, 'Dreams That Money Can Buy', 'Fantasy', 3.0);
insert into movies (id, movie_title, movie_genre, movie_rating) values (7, 'Skyscraper Souls', 'Drama|Romance', 4.6);
insert into movies (id, movie_title, movie_genre, movie_rating) values (8, 'Oh, God! You Devil', 'Comedy', 9.8);
insert into movies (id, movie_title, movie_genre, movie_rating) values (9, 'Southerner, The', 'Drama', 5.6);
insert into movies (id, movie_title, movie_genre, movie_rating) values (10, 'DarkBlueAlmostBlack (Azuloscurocasinegro)', 'Drama|Romance', 7.6);
insert into movies (id, movie_title, movie_genre, movie_rating) values (11, 'Destinées, Les (Destinées sentimentales, Les)', 'Drama|Romance', 5.7);
insert into movies (id, movie_title, movie_genre, movie_rating) values (12, 'Ice Age Columbus: Who Were the First Americans?', 'Documentary', 3.8);
insert into movies (id, movie_title, movie_genre, movie_rating) values (13, 'Satanas', 'Crime|Drama', 5.8);
insert into movies (id, movie_title, movie_genre, movie_rating) values (14, 'Radio Free Albemuth', 'Drama|Sci-Fi', 4.0);
insert into movies (id, movie_title, movie_genre, movie_rating) values (15, 'Frantic', 'Crime|Mystery|Thriller', 5.0);
insert into movies (id, movie_title, movie_genre, movie_rating) values (16, 'Cialo', 'Comedy|Crime', 9.9);
insert into movies (id, movie_title, movie_genre, movie_rating) values (17, 'Szamanka', 'Drama|Horror|Mystery', 7.0);
insert into movies (id, movie_title, movie_genre, movie_rating) values (18, 'Clara''s Heart', 'Drama', 8.6);
insert into movies (id, movie_title, movie_genre, movie_rating) values (19, 'Mike''s New Car', 'Animation|Comedy', 7.7);
insert into movies (id, movie_title, movie_genre, movie_rating) values (20, '55 Days at Peking', 'Drama|War', 7.8);
insert into movies (id, movie_title, movie_genre, movie_rating) values (21, 'Air Raid Wardens', 'Children|Comedy', 6.2);
insert into movies (id, movie_title, movie_genre, movie_rating) values (22, 'Welcome to the Sticks (Bienvenue chez les Ch''tis)', 'Comedy', 9.6);
insert into movies (id, movie_title, movie_genre, movie_rating) values (23, 'Stella Street', 'Comedy', 6.3);
insert into movies (id, movie_title, movie_genre, movie_rating) values (24, 'Traviata, La', 'Drama|Musical', 5.0);
insert into movies (id, movie_title, movie_genre, movie_rating) values (25, 'Better Off Dead...', 'Comedy|Romance', 5.1);
insert into movies (id, movie_title, movie_genre, movie_rating) values (26, '300: Rise of an Empire', 'Action|Drama|War|IMAX', 9.2);
insert into movies (id, movie_title, movie_genre, movie_rating) values (27, 'Family Business', 'Comedy', 3.8);
insert into movies (id, movie_title, movie_genre, movie_rating) values (28, 'Fidel', 'Documentary', 4.5);
insert into movies (id, movie_title, movie_genre, movie_rating) values (29, 'Before I Go to Sleep', 'Mystery|Thriller', 9.8);
insert into movies (id, movie_title, movie_genre, movie_rating) values (30, 'Sube y Baja', 'Comedy', 3.1);
insert into movies (id, movie_title, movie_genre, movie_rating) values (31, 'Story of G.I. Joe', 'War', 4.3);
insert into movies (id, movie_title, movie_genre, movie_rating) values (32, 'Charly', 'Comedy|Drama|Romance', 9.8);
insert into movies (id, movie_title, movie_genre, movie_rating) values (33, 'Charm''s Incidents (Charms Zwischenfälle)', 'Drama', 7.6);
insert into movies (id, movie_title, movie_genre, movie_rating) values (34, 'Serbian Film, A (Srpski film)', 'Horror|Thriller', 8.3);
insert into movies (id, movie_title, movie_genre, movie_rating) values (35, 'Hometown Legend', 'Drama', 6.3);
insert into movies (id, movie_title, movie_genre, movie_rating) values (36, 'Halfmoon (Paul Bowles - Halbmond)', 'Drama', 9.2);
insert into movies (id, movie_title, movie_genre, movie_rating) values (37, 'Shoes of the Fisherman, The', 'Drama', 5.9);
insert into movies (id, movie_title, movie_genre, movie_rating) values (38, 'Hannah and Her Sisters', 'Comedy|Drama|Romance', 3.4);
insert into movies (id, movie_title, movie_genre, movie_rating) values (39, 'Sacrificio: Who Betrayed Che Guevara', 'Documentary', 7.7);
insert into movies (id, movie_title, movie_genre, movie_rating) values (40, 'Love Before Breakfast', 'Comedy|Romance', 6.9);
insert into movies (id, movie_title, movie_genre, movie_rating) values (41, 'Strange Bedfellows', 'Comedy', 4.4);
insert into movies (id, movie_title, movie_genre, movie_rating) values (42, 'Skies Above the Landscape (Nebo iznad krajolika)', 'Comedy', 7.8);
insert into movies (id, movie_title, movie_genre, movie_rating) values (43, 'Mon Oncle Antoine', 'Drama', 8.0);
insert into movies (id, movie_title, movie_genre, movie_rating) values (44, 'Thunderbolt (Pik lik feng)', 'Action|Crime', 5.8);
insert into movies (id, movie_title, movie_genre, movie_rating) values (45, 'Carnage', 'Comedy|Drama', 6.0);
insert into movies (id, movie_title, movie_genre, movie_rating) values (46, 'Law of Desire (Ley del deseo, La)', 'Comedy|Drama|Romance', 6.3);
insert into movies (id, movie_title, movie_genre, movie_rating) values (47, 'Phil Ochs: There But for Fortune', 'Documentary|Musical', 8.5);
insert into movies (id, movie_title, movie_genre, movie_rating) values (48, 'Lost Youth', '(no genres listed)', 3.5);
insert into movies (id, movie_title, movie_genre, movie_rating) values (49, 'Marwencol', 'Documentary', 5.5);
insert into movies (id, movie_title, movie_genre, movie_rating) values (50, 'Maniac', 'Crime|Horror|Mystery|Romance|Thriller', 9.1);
insert into movies (id, movie_title, movie_genre, movie_rating) values (51, 'Blueprint for Murder, A', 'Film-Noir|Mystery|Thriller', 9.0);
insert into movies (id, movie_title, movie_genre, movie_rating) values (52, 'Tracers', 'Action', 4.4);
insert into movies (id, movie_title, movie_genre, movie_rating) values (53, 'Lunacy (Sílení)', 'Animation|Horror', 5.7);
insert into movies (id, movie_title, movie_genre, movie_rating) values (54, 'Love Story', 'Drama|Romance', 4.0);
insert into movies (id, movie_title, movie_genre, movie_rating) values (55, 'Coluche, l''histoire d''un mec', 'Drama', 5.6);
insert into movies (id, movie_title, movie_genre, movie_rating) values (56, 'Gravity (Schwerkraft)', 'Crime|Drama|Romance', 5.2);
insert into movies (id, movie_title, movie_genre, movie_rating) values (57, 'Snake River Desperadoes', 'Western', 8.2);
insert into movies (id, movie_title, movie_genre, movie_rating) values (58, 'New Barbarians, The (I nuovi barbari)', 'Action|Sci-Fi|Thriller|Western', 3.2);
insert into movies (id, movie_title, movie_genre, movie_rating) values (59, 'Gregory Crewdson: Brief Encounters', 'Documentary|Drama', 8.7);
insert into movies (id, movie_title, movie_genre, movie_rating) values (60, 'Party Monster', 'Documentary', 8.8);
insert into movies (id, movie_title, movie_genre, movie_rating) values (61, 'No Direction Home: Bob Dylan', 'Documentary', 6.2);
insert into movies (id, movie_title, movie_genre, movie_rating) values (62, 'Concert, Le', 'Comedy|Drama', 7.4);
insert into movies (id, movie_title, movie_genre, movie_rating) values (63, 'Powder Room', 'Comedy', 3.7);
insert into movies (id, movie_title, movie_genre, movie_rating) values (64, 'Wrong Turn 3: Left for Dead', 'Horror', 4.9);
insert into movies (id, movie_title, movie_genre, movie_rating) values (65, 'Kindergarten Cop', 'Action|Comedy|Crime|Thriller', 6.7);
insert into movies (id, movie_title, movie_genre, movie_rating) values (66, 'Departures (Okuribito)', 'Drama', 7.0);
insert into movies (id, movie_title, movie_genre, movie_rating) values (67, 'Hugo Pool', 'Romance', 5.4);
insert into movies (id, movie_title, movie_genre, movie_rating) values (68, 'Blood Shot', 'Action|Comedy|Horror', 9.5);
insert into movies (id, movie_title, movie_genre, movie_rating) values (69, 'Things We Do For Love (Kaikella rakkaudella)', 'Drama', 9.5);
insert into movies (id, movie_title, movie_genre, movie_rating) values (70, 'Grifters, The', 'Crime|Drama|Film-Noir', 3.3);
insert into movies (id, movie_title, movie_genre, movie_rating) values (71, 'Eyes Wide Open (Einayim Petukhoth)', 'Drama', 7.8);
insert into movies (id, movie_title, movie_genre, movie_rating) values (72, 'Creation', 'Drama', 6.0);
insert into movies (id, movie_title, movie_genre, movie_rating) values (73, 'Thunder Bay', 'Adventure', 3.8);
insert into movies (id, movie_title, movie_genre, movie_rating) values (74, 'Cranes Are Flying, The (Letyat zhuravli)', 'Drama|Romance|War', 7.7);
insert into movies (id, movie_title, movie_genre, movie_rating) values (75, 'China Syndrome, The', 'Drama|Thriller', 6.3);
insert into movies (id, movie_title, movie_genre, movie_rating) values (76, 'All I Want for Christmas', 'Children|Comedy', 5.2);
insert into movies (id, movie_title, movie_genre, movie_rating) values (77, 'City of Hope', 'Drama', 7.4);
insert into movies (id, movie_title, movie_genre, movie_rating) values (78, 'Naked City, The', 'Crime|Drama|Film-Noir|Mystery', 9.8);
insert into movies (id, movie_title, movie_genre, movie_rating) values (79, 'Where Are the Dreams of Youth? (Seishun no yume imaizuko)', 'Drama', 4.1);
insert into movies (id, movie_title, movie_genre, movie_rating) values (80, 'Sound and Fury', 'Documentary', 8.9);
insert into movies (id, movie_title, movie_genre, movie_rating) values (81, 'Mile... Mile & a Half', 'Documentary', 6.6);
insert into movies (id, movie_title, movie_genre, movie_rating) values (82, 'The Girls', 'Comedy', 6.9);
insert into movies (id, movie_title, movie_genre, movie_rating) values (83, 'Bang, Bang, You''re Dead', 'Drama', 3.4);
insert into movies (id, movie_title, movie_genre, movie_rating) values (84, 'Kiss Before Dying, A', 'Film-Noir|Mystery', 3.7);
insert into movies (id, movie_title, movie_genre, movie_rating) values (85, 'Boy', 'Drama|Romance', 8.3);
insert into movies (id, movie_title, movie_genre, movie_rating) values (86, 'Someone''s Watching Me!', 'Horror|Mystery|Thriller', 4.4);
insert into movies (id, movie_title, movie_genre, movie_rating) values (87, 'Day Is Done', 'Documentary', 5.1);
insert into movies (id, movie_title, movie_genre, movie_rating) values (88, 'Thursday', 'Action|Crime|Thriller', 9.1);
insert into movies (id, movie_title, movie_genre, movie_rating) values (89, 'Keoma', 'Action|Drama|Western', 7.4);
insert into movies (id, movie_title, movie_genre, movie_rating) values (90, 'Canciones de amor en Lolita''s Club', 'Drama', 5.6);
insert into movies (id, movie_title, movie_genre, movie_rating) values (91, 'Bright Future (Akarui mirai)', 'Drama', 3.9);
insert into movies (id, movie_title, movie_genre, movie_rating) values (92, 'Madeline', 'Children|Comedy', 4.8);
insert into movies (id, movie_title, movie_genre, movie_rating) values (93, 'Punk in London', 'Documentary|Musical', 7.1);
insert into movies (id, movie_title, movie_genre, movie_rating) values (94, 'I''m Not Rappaport', 'Comedy', 6.0);
insert into movies (id, movie_title, movie_genre, movie_rating) values (95, 'Machete Kills (Machete 2)', 'Action|Crime|Thriller', 8.3);
insert into movies (id, movie_title, movie_genre, movie_rating) values (96, 'Rashomon (Rashômon)', 'Crime|Drama|Mystery', 6.9);
insert into movies (id, movie_title, movie_genre, movie_rating) values (97, 'I Accuse', 'Crime|Drama|Thriller', 9.3);
insert into movies (id, movie_title, movie_genre, movie_rating) values (98, 'Eiger Sanction, The', 'Action|Adventure|Drama|Thriller', 3.3);
insert into movies (id, movie_title, movie_genre, movie_rating) values (99, 'Floating', 'Drama', 9.5);
insert into movies (id, movie_title, movie_genre, movie_rating) values (100, 'Morphia (Morfiy)', 'Drama', 5.7);